#!/bin/bash

echo "\e]P02a2331" #black
echo "\e]P1E83F80" #darkred
echo "\e]P2A2BAA8" #darkgreen
echo "\e]P3EACAC0" #darkyellow
echo "\e]P49985D1" #darkblue
echo "\e]P5E68AC1" #darkmagenta
echo "\e]P6AABAE7" #darkcyan
echo "\e]P74e3e5e" #gray
echo "\e]P8302838" #darkgray
echo "\e]P9F55D8F" #red
echo "\e]PABFD1C3" #green
echo "\e]PBF0DDD8" #yellow
echo "\e]PCB4A4DE" #blue
echo "\e]PDEDABD2" #magenta
echo "\e]PEC4D1F5" #cyan
echo "\e]PFDEDBEB" #white
#echo "\e]P?231d29" #darkblack
clear #gets rid of artifacts
